### ISSUE TITLE
Blog post: Downloading content stored on Filecoin

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#102]
See https://www.notion.so/pl-strflt/How-to-Retrieve-Content-Stored-in-Filecoin-Deals-47e4469fa4ed4018b095eaa89396cd32?pvs=4#dd4fa11804ce469da236fae1b800eee2 and https://github.com/filecoin-station/roadmap/issues/65

- [x] Write & publish the blog post
- [x] Mention the post in docs: [Retrieval With Attestation](https://filspark.com/retrieval-attestation)

**Comment by bajtos** [comment]
Blog post draft: https://www.notion.so/spacemeridian/How-SPARK-Retrieves-Content-Stored-on-Filecoin-df081fb20c7040f7984562e4182bb37c

**Comment by juliangruber** [comment]
Are you going to publish this on X and other channels?

**Comment by bajtos** [comment]
> Are you going to publish this on X and other channels?

Great suggestion!
