### ISSUE TITLE
Move our Grafana dashboards to spacemeridian.grafana.net

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#105]
### Public Dashboards
- [x] [Spark Public Dashboard](https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c)
- [x] [Station Public Dashboard](https://bajtos.grafana.net/public-dashboards/65f9a9da793c4644a1b6b5ed688130aa)

Out of scope:
- Custom domain for Station dashboard: dash.filstation.app
- Custom domain for Spark dashboard: dash.filspark.com

### Internal DevOps Dashboards
- Migrate remaining data sources from Protocol Labs Grafana
  - [x] Filecoin Station Downloads API
  - [x] <del>Filecoin Station GitHub releases</del> (not used)
  - [x] Filecoin Station Plausible
- [x] [Meridian](https://protocollabs.grafana.net/d/ce0a7c99-2871-4f1d-95bb-6688b062762c/meridian)
- [x] [SPARK](https://protocollabs.grafana.net/d/c4bd3c80-9360-4ea3-8b75-c5ecea90765b/spark)
- [x] [SPARK DB](https://protocollabs.grafana.net/d/e76dcd12-eb76-4db4-b818-472d945d353c/spark-db)
- [x] [Station](https://protocollabs.grafana.net/d/F2UmmYnVk/station)
- [x] Migrate all alerts and ensure they send notifications to SpaceMeridian workspace
  - [x] @juliangruber 
    - [x] Meridian
      - [x] Available Balance
      - [x] Balances (FIL) alert
      - [x] Rounds alert
    - [x] Station
      - [x] All Stations Running alert
  - [x] @bajtos - Spark
    - [x] spark-api internal errors alert
    - [x] spark-publish load alert
    - [x] Unpublished measurements (Max Age) alert
    - [x] SPARK DB capacity alert
    - [x] spark-api request concurrency alert
    - [x] spark-api response times alert
    - [ ] spark-stats internal errors alert
- [x] Decide what to do with [Station Public](https://protocollabs.grafana.net/d/e4d5bd1c-c5c3-406f-a58a-2e60c4089cde/station-public) and how to merge those charts with the new Station Public Dashboard we are building

### Cleanup

Remove Station/Spark/Voyager datasources from Protocol Labs Grafana account - see https://protocollabs.grafana.net/connections/datasources:

- [x] [Filecoin Station Downloads API](https://protocollabs.grafana.net/dashboard/new-with-ds/3BFFyRdVz)
- [x] [Filecoin Station Fly.io
](https://protocollabs.grafana.net/dashboard/new-with-ds/aaf20e1e-3d67-43ca-8954-abb36b2552cd)
- [x] [Filecoin Station GitHub releases](https://protocollabs.grafana.net/dashboard/new-with-ds/r00FzgV4k)
- [x] [Filecoin Station InfluxDB](https://protocollabs.grafana.net/dashboard/new-with-ds/tyXvLv4Vk)
- [x] [Filecoin Station Plausible](https://protocollabs.grafana.net/dashboard/new-with-ds/ZXyclROVk)
- [x] [Filecoin Station Spark PostgreSQL](https://protocollabs.grafana.net/dashboard/new-with-ds/c2397784-8e05-4834-ba15-81471427b9e0)
- [x] [Spark InfluxDB](https://protocollabs.grafana.net/dashboard/new-with-ds/f9c447c1-b044-4321-95ee-bfaf386e7c83)
- [x] [SPARK Stats](https://protocollabs.grafana.net/dashboard/new-with-ds/a2d8b2fa-9bf1-4146-ab57-197becb67741)

Close or rework older Grafana-related tasks:
- [x] #72
- [x] #57

**Comment by juliangruber** [comment]
Station dashboard was migrated https://spacemeridian.grafana.net/d/F2UmmYnVk/station?orgId=1

**Comment by juliangruber** [comment]
Next is to migrate the alerts.

@bajtos let's discuss this in the kickoff call, or do you have an idea how we could best do this?

**Comment by bajtos** [comment]
> Next is to migrate the alerts.
> 
> @bajtos let's discuss this in the kickoff call

SGTM 👍🏻 

> or do you have an idea how we could best do this?

Not from the top of my head 😞

**Comment by bajtos** [comment]
IMO, we need to migrate the alerts first, as these alerts are reading data from the datasources, right?

**Comment by juliangruber** [comment]
Then I'll unsassign myself for the time being :)

**Comment by bajtos** [comment]
I migrated Spark alerts to SpaceMeridan's Grafana instance.

I am assigning the issue back to you, @juliangruber, so that you can perform the final cleanup. I don't have admin permissions to PL Grafana. Therefore, I cannot perform actions like deleting data sources.

In addition to _"Remove Station/Spark/Voyager datasources"_, I think we should also remove our dashboards and alerts. WDYT?

**Comment by juliangruber** [comment]
All completed
