### ISSUE TITLE
Log IPv4/ location data and serve it in the public dashboard while preserving privacy

### ISSUE THREAD

**Issue by PatrickNercessian** [space-meridian/roadmap#112]
Sub-issue to https://github.com/filecoin-station/roadmap/issues/97

**Comment by PatrickNercessian** [comment]
We previously discussed that CloudFlare has optional location headers that we can include in requests to spark-api.

https://developers.cloudflare.com/rules/transform/managed-transforms/reference/#add-visitor-location-headers

Thus, in spark-api, we can store this data in InfluxDB, to be consumed by [spark-observer](https://github.com/filecoin-station/spark-stats/tree/1146262d9da2013c2f3a39c782f5b6f1e9901327/observer). This is similar to the approach discussed in #98.

The end goal is to have a public visualization of geolocation of nodes (while preserving privacy), and a dashboard of the total number of IPv4 subnets over time.

**Comment by PatrickNercessian** [comment]
Any thoughts on the above visualization tools? @bajtos @juliangruber @patrickwoodhead

**Comment by juliangruber** [comment]
While we use Grafana, let's just use what Grafana offers?

**Comment by bajtos** [comment]
Closing as done.
