### ISSUE TITLE
M4.6 Get ready for EthCC & FDS 🚀

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#116]
_Previous milestone: [M4.5](https://github.com/space-meridian/roadmap/issues/104)_
_Next milestone: https://github.com/space-meridian/roadmap/issues/121_

:shipit: 🇧🇪 

ETA: 2024-07-08

- [x] https://github.com/filecoin-station/desktop/issues/1612 (@juliangruber) 
- [x] #129
- [x] https://github.com/space-meridian/roadmap/issues/57 (@bajtos)
- [x] #114 (@juliangruber)
- [ ] #130
- [x] Spark Presentation with complete clarity over what we are working on and shipping (@patrickwoodhead)
- [x] Create job spec for new role on team (@patrickwoodhead )

## Stretch goals

- [x] https://github.com/filecoin-station/roadmap/issues/100 (@bajtos)
- [ ] #71 @juliangruber 
- [ ] #94 @juliangruber @patrickwoodhead 
- [ ] https://github.com/space-meridian/roadmap/issues/117

**Comment by juliangruber** [comment]
All remaining issues added to https://github.com/space-meridian/roadmap/issues/121
