### ISSUE TITLE
Finish nucleation migration

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#117]
See https://docs.google.com/document/d/1gYm5g9kRNo6PLihpvOFDPJRnF9jQygMwWn7BfxIdbRM/edit#heading=h.gxxljjm812bt

**Comment by juliangruber** [comment]
W3S migration is blocked by https://github.com/storacha-network/w3infra/pull/392

**Comment by juliangruber** [comment]
D-U-N-S is also blocked, waiting for a reply from Apple support

**Comment by bajtos** [comment]
@juliangruber @patrickwoodhead 

How about creating follow-up issues for "W3S migration" and "D-U-N-S/Apple Dev Account" so that we can close this large milestone and continue tracking only those two smaller tasks?

I think the third remaining task is to transfer https://meridian.space/ to DNSSimple, @patrickwoodhead is the DRI.

**Comment by juliangruber** [comment]
+1 to creating issues
- W3S migration
- Apple dev account migration
- meridian.space migration

**Comment by juliangruber** [comment]
Domain migration: https://github.com/space-meridian/roadmap/issues/133

**Comment by patrickwoodhead** [comment]
Close, break down and create more granular tickets

**Comment by juliangruber** [comment]
- https://github.com/space-meridian/roadmap/issues/159
- https://github.com/space-meridian/roadmap/issues/160
