### ISSUE TITLE
Retrieval status breakdown in public dashboard

### ISSUE THREAD

**Issue by juliangruber** [space-meridian/roadmap#123]
- [x] [Public dashboard v2](https://github.com/filecoin-station/spark-dashboard/pull/1)
- [ ] Public dashboard v1

There were multiple requests at FDS to move this to the public spark dashboard:

![Screenshot 2024-07-09 at 16 46 06](https://github.com/user-attachments/assets/60a2d7de-aa2a-4baf-805f-97e3853bbc44)

Feedback by @bajtos:

> For the Retrieval Status breakdown, I think we should reduce the granularity to make this data easier to understand for people that are not familiar with Spark internals. I think there should be only two IPNI-related statuses - “CID not advertised by SP” and “cid.contact query failed”.

**Comment by bajtos** [comment]
Let's use per-deal retrieval score for this new chart.

Prerequisite:
- https://github.com/filecoin-station/spark-evaluate/pull/336

**Comment by juliangruber** [comment]
Since we're going to migrate everything to dashboard v2, I'm not going to bother with adding this to v1
