### ISSUE TITLE
Create Spark v2 roadmap with months until end of 2024

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#141]

**Comment by patrickwoodhead** [comment]
@bajtos - please review the high level draft at https://www.notion.so/spacemeridian/Spark-Roadmap-2024-fd55c1fa851e425ab8fa988f1088521a?pvs=4

**Comment by bajtos** [comment]
Related:
- https://github.com/space-meridian/roadmap/issues/115
- https://starmap.site/roadmap/github.com/space-meridian/roadmap/issues/115#view=list
