### ISSUE TITLE
Spark on-chain oracle

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#145]
eta: 2024-11-06

Implement an on-chain oracle that other smart contracts can call to get retrieval success rate and other information about miners/clients/allocators.

- [x] Find out what data the Dashboard needs
- [x] Figure out how it wants to consume them
- [x] Figure out what is the easiest way for Spark to offer the data
- [x] Write a smart contract
- [x] Require payments for getting data (will be added later)
- [x] Evaluate getting an audit
- [x] Publish data from `spark-evaluate`
- [x] Document smart contract
- [x] Add monitoring
- [x] Announce smart contract (will be done later)

**Comment by juliangruber** [comment]
I would love to work on this or lend a hand

**Comment by bajtos** [comment]
Moving from the preliminary M4.10 list:
> Brainstorm: Can we publish evaluation results on chain? Which data needs to go on chain? Just RSR?

**Comment by juliangruber** [comment]
Added todos from https://github.com/space-meridian/roadmap/issues/179
