### ISSUE TITLE
Migrate to new billing email in web3storage

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#150]
- [x] Create new Storacha account
- [ ] Point existing services at new account
- [ ] Evaluate closing old account

**Comment by bajtos** [comment]
- Let's create new SpaceMeridian account and use it for publishing new measurements going forward.
- We can keep the old account around ($100/month) and figure out what to do with it later. It's also an option to close it and lose access to historical measurements.

**Comment by juliangruber** [comment]
I was able to set the billing email for the old account to julian@meridian.space. I believe this deprioritizes the issue now, as we can ensure access to invoices
