### ISSUE TITLE
Lessons learned from running Meridian on FEVM

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#157]
In the past 12 months, we learned a lot about the practical aspects of running a Web 2.5 service interacting with FEVM smart contract via RPC API. What worked well? What are the rough edges that the Filecoin developers could improve?

I'd like to present our learnings at FIL Dev Summit at LabWeek.

We can also convert the talk into a blog post after the event.

List of topics we could mention:

- Gas fee estimation - ethers.js v5, ethers.js v6

- Rising gas fees, stuck transactions, how to recover. 
   - Don't resubmit the transactions!
   - How to cancel pending transaction.

- Reliability and performance of RPC API providers

- How to reliably consume smart contract events (polling vs websockets, filters, etc.)

- How to self-heal service state after deploying a new version (see https://github.com/filecoin-station/spark-evaluate/issues/3)

**Comment by bajtos** [comment]
@juliangruber, could you please add anything else that comes to mind? I remember you had one idea last week, but I cannot recall it.

**Comment by juliangruber** [comment]
- Getting filecoin native addresses to work in the contract is tricky. I didn't manage to do so, this is why we switched to 0x addresses. Also, other tooling like ethers.js wouldn't support it. https://github.com/Meridian-IE/impact-evaluator/issues/28
- There's no publicly hosted Filecoin L2 yet. But: We're part of the IPC WG now
- Filecoin testnet (calibration) is way easier to use than EVM testnets (you have to perform some work to get test ether, you can't just use a faucet)

> How to self-heal service state after deploying a new version (see https://github.com/filecoin-station/spark-evaluate/issues/3)

I believe this has nothing to do with FEVM vs EVM, but still can be mentioned.

**Comment by juliangruber** [comment]
I'll keep editing this comment with ideas :)

**Comment by bajtos** [comment]
@juliangruber here is the list of ideas we had for the Infra Tooling talk.

Adding ideas we discussed this week.

- Lack of reliable RPC API providers, we can use only Glif
- We really need L2 - a public IPC deployment that can run Solidity contracts and roll up to L1
- Compatibility with Ethereum tooling (RPC API client libraries like Ethers.js)
- DX when using Filecoin addresses (vs Ethereum 0x addresses)
- No tooling to check gas fee estimation - how can we find out whether we are overspending or underspending?
- It would be great if we could programmatically generate a unique access token for each Station Desktop/Core instance and don’t have to publicly put the “master” token created using one of our wallets. Something like a delegated token, where the Station receives a voucher that it can exchange for an access token that’s linked to our account (“master” token).
  That way we can keep the “master” token private. If we find that somebody is abusing the delegated token they received, we can revoke only that one token and keep the rest of the users unaffected.
  This also opens an opportunity to implement things like rate-limiting on how many delegated tokens can be created from a given IPv4 network, etc.

**Comment by juliangruber** [comment]
Slides: https://docs.google.com/presentation/d/1gFs_Aiy86Kp8kNg3ybbZd0nLNhdpXbanaReKgEFjvG4/edit?usp=sharing

Talk: https://www.youtube.com/watch?v=v_HP30hLvtQ
