### ISSUE TITLE
Move L1 scores to `spark-rewards`

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#161]
- [x] https://github.com/filecoin-station/core/pull/606
- [x] https://github.com/filecoin-station/spark-stats/pull/234
- [x] https://github.com/filecoin-station/spark-rewards/issues/13
- [x] https://github.com/filecoin-station/spark-evaluate/pull/338

**Comment by bajtos** [comment]
Cross-posting from Slack:

Please remember to update spark-observer as part of your work on spark-rewards.
https://github.com/filecoin-station/spark-stats/blob/a6455da4c58810a3e32b83adbaaef7dd5ba8ecdd/observer/lib/observer.js#L43-L73
