### ISSUE TITLE
Expose deal count per SP, in addition to SRS

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#162]

**Comment by bajtos** [comment]
I believe this was already done via:
- https://github.com/filecoin-station/spark/issues/78 
- https://github.com/filecoin-station/spark-stats/pull/194

Example URL:

https://api.filspark.com/miner/f0814049/deals/eligible/summary

Did you perhaps have something else in mind, @patrickwoodhead? Could you please update the issue title and add more details to the issue description to clarify?
