### ISSUE TITLE
Get list of Filecoin wallets onboarded through Spark/Station

### ISSUE THREAD

**Issue by bajtos** [space-meridian/roadmap#170]
- [x] List all participant addresses @bajtos 
  - https://github.com/filecoin-station/spark-stats/pull/232
  - https://gist.github.com/bajtos/0fb8985e3f5928c5c31ff7a28e1260ab
- [x] Check if participant has transactions before Spark/Station @juliangruber

**Comment by bajtos** [comment]
We want to show our impact in our application for FIL-RetroPGF Round 2. 

Quoting from https://github.com/filecoin-project/community/discussions/714:
> Round 2 involves distributing 300K FIL to projects that have shown impact in the previous 6 months (April - September 2024).

I ran a query to find Spark participants first seen between April and September 2024 and found 37,231 addresses.

See https://gist.github.com/bajtos/3b68c2f9a654bcc755fc5f428dfd37ba

**Comment by juliangruber** [comment]
Here's the list filtered by who was onboarded by Station/Spark (see also script included): https://gist.github.com/juliangruber/3225e37d1dd8e819b0b745f22b6816a7#file-01-onboarded-txt
