### ISSUE TITLE
Setup GitHub Actions for spark-stats Cloudflare Worker

### ISSUE THREAD

**Issue by pyropy** [space-meridian/roadmap#211]
We need to setup Github Actions to automate testing and deployment of [cloudflare worker used](https://github.com/filecoin-station/cf-metrics) for gathering request metrics for spark-stats.

Part of #206

**Comment by juliangruber** [comment]
Set up GitHub Actions for what? Did you mean to open this issue on https://github.com/filecoin-station/cf-metrics? If so, please move it there

**Comment by pyropy** [comment]
Moving to https://github.com/filecoin-station/cf-metrics/issues/4

**Comment by pyropy** [comment]
> Set up GitHub Actions for what? Did you mean to open this issue on https://github.com/filecoin-station/cf-metrics? If so, please move it there

Sorry, I have created this issue automatically from issue #206. I'm going to open issues in relevant repositories in the future.
