### ISSUE TITLE
Build a Public Spark Dashboard in our new Grafana account

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#72]
Move https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1 to our own Grafana instance.

**Comment by patrickwoodhead** [comment]
Awaiting nucleation to finish this.

**Comment by bajtos** [comment]
Done. https://spacemeridian.grafana.net/public-dashboards/32c03ae0d89748e3b08e0f08121caa14?orgId=1
