### ISSUE TITLE
Add Meridian infrastructure for Voyager

### ISSUE THREAD

**Issue by patrickwoodhead** [space-meridian/roadmap#73]

**Comment by juliangruber** [comment]
- https://github.com/filecoin-station/voyager-impact-evaluator
- https://github.com/filecoin-station/voyager-api

**Comment by bajtos** [comment]
@juliangruber @patrickwoodhead is this still relevant? Can we close this issue as done or not planned?

**Comment by juliangruber** [comment]
Yes, not planned
