### ISSUE TITLE
Track Deployment Type and device info and serve it for public dashboard

### ISSUE THREAD

**Issue by PatrickNercessian** [space-meridian/roadmap#98]
Sub-issue to https://github.com/filecoin-station/roadmap/issues/97

**Comment by PatrickNercessian** [comment]
We have discussed setting up a new service, spark-observer, for searching for FIL Transfer events, in order to update a new daily_fil table. Infrastructure for this is being tracked in https://github.com/filecoin-station/roadmap/issues/109

Based on discussion in https://github.com/filecoin-station/core/pull/411, we can potentially use this new spark-observer service to also periodically read device info stats from InfluxDB.

Furthermore, we can take inspiration from https://github.com/filecoin-station/core/pull/411 PR to also start tracking deployment type in a similar manner, and have spark-observer periodically read that as well.

Any thoughts @juliangruber @bajtos?

**Comment by bajtos** [comment]
> Based on discussion in https://github.com/filecoin-station/core/pull/411, we can potentially use this new spark-observer service to also periodically read device info stats from InfluxDB.
>
> Furthermore, we can take inspiration from the same PR to also start tracking deployment type in a similar manner (edit: wait, it looks like this is already being done? ([link](https://github.com/filecoin-station/core/blob/7d1354ac9cc31f895e704f462f51db6c24c9a888/lib/telemetry.js#L68)), and have spark-observer periodically read that as well. We discussed this further in https://github.com/filecoin-station/zinnia/pull/526

It makes sense to me to put the code periodically reading from InfluxDB into this new spark-observer service 👍🏻

**Comment by PatrickNercessian** [comment]
I was able to instead get our Grafana dashboard to read directly from InfluxDB
